# Options Rakefile

require 'rubygems'
require 'rubygems/package'
require 'rake'
require 'rake/clean'
$LOAD_PATH << 'lib'

spec = Gem::Specification::load("options.gemspec")
target = "#{spec.name}-#{spec.version}.gem"

desc 'Test gem'
task :test do
  ruby "test/test_options.rb"
end

desc 'Default is build'
task :default => [:build]

desc 'Build gem'
task :build => [:clean] do
  Gem::Package.build spec, true
end
 
desc 'Install gem'
task :install do
  Gem::Package.install spec
end
 
CLEAN.include "#{target}"
